FROM node:9

WORKDIR /src

COPY package-lock.json /src/package-lock.json
COPY package.json /src/package.json
COPY conf.ambiente.js /src/constants/index.js

##RUN set -x \
##    && apt-get update \
##    && alias python2=
 

#RUN set -x \
#    && npm update \
#    && npm i -g concurrently node-sass
    


#RUN sudo npm rebuild node-sass --force 

#RUN yarn install \
#    && yarn


#CMD concurrently "yarn start" "yarn watch-css"