# Frontend Build
FROM node:9-alpine

WORKDIR /src

COPY ./package.json ./yarn.lock /src/

RUN set -x \
    && yarn

COPY . /src/

RUN set -x \
    && yarn build

# Imagem final
FROM nginx

COPY --from=0 /src/build /usr/share/nginx/html